"""esquema inicial

Revision ID: a86744b415ba
Revises: 
Create Date: 2026-07-19 21:38:31.588083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a86744b415ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_headquarters', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_units_code'), ['code'], unique=True)

    op.create_table('schema_definitions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_definitions_version'), ['version'], unique=True)

    op.create_table('elements',
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('element_type', sa.String(length=64), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('parent_guid', sa.String(length=64), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['un_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elements_element_type'), ['element_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_elements_guid'), ['guid'], unique=True)
        batch_op.create_index(batch_op.f('ix_elements_parent_guid'), ['parent_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_elements_un_id'), ['un_id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['un_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('un_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_params_version', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['un_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_device_uid'), ['device_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_un_id'), ['un_id'], unique=False)

    op.create_table('quality_param_sets',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_param_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_param_sets_version'), ['version'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('works',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sector_geojson', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=True),
    sa.Column('validation_result', sa.String(length=16), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['un_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_works_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_work_type'), ['work_type'], unique=False)

    op.create_table('element_logs',
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('element_guid', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('work_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('element_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_logs_element_guid'), ['element_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_logs_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_logs_event_type'), ['event_type'], unique=False)

    op.create_table('field_changes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('work_code', sa.String(length=64), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('element_guid', sa.String(length=64), nullable=False),
    sa.Column('element_type', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=8), nullable=False),
    sa.Column('attributes_before', sa.Text(), nullable=True),
    sa.Column('attributes_after', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_changes_element_guid'), ['element_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_work_code'), ['work_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_changes_work_id'), ['work_id'], unique=False)

    op.create_table('gis_staging_batches',
    sa.Column('un_code', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queue_seq', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gis_staging_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gis_staging_batches_queue_seq'), ['queue_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_staging_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_staging_batches_un_code'), ['un_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_staging_batches_work_id'), ['work_id'], unique=False)

    op.create_table('remote_delete_orders',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ordered_by_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_delete_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_delete_orders_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_delete_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_delete_orders_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_delete_orders_work_id'), ['work_id'], unique=False)

    op.create_table('sync_packages',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('validation_result', sa.String(length=16), nullable=False),
    sa.Column('validation_report_json', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('consolidated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_packages_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_packages_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_packages_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_packages_work_id'), ['work_id'], unique=False)

    op.create_table('work_elements',
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('element_guid', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_elements_element_guid'), ['element_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_elements_work_id'), ['work_id'], unique=False)

    op.create_table('gis_staging_elements',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=8), nullable=False),
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('element_type', sa.String(length=64), nullable=False),
    sa.Column('parent_guid', sa.String(length=64), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['gis_staging_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gis_staging_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gis_staging_elements_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_staging_elements_guid'), ['guid'], unique=False)

    op.create_table('photos',
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('element_guid', sa.String(length=64), nullable=True),
    sa.Column('work_id', sa.String(length=36), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('gps_lon', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('received_chunks', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('fully_received', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['sync_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_element_guid'), ['element_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_sha256'), ['sha256'], unique=False)

    op.create_table('quality_novelties',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('un_id', sa.String(length=36), nullable=False),
    sa.Column('element_guid', sa.String(length=64), nullable=True),
    sa.Column('element_type', sa.String(length=64), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('rule_type', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expected', sa.String(length=255), nullable=True),
    sa.Column('actual', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['sync_packages.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_novelties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_novelties_element_guid'), ['element_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_novelties_element_type'), ['element_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_novelties_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_novelties_rule_type'), ['rule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_novelties_un_id'), ['un_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_novelties_work_id'), ['work_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_novelties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_novelties_work_id'))
        batch_op.drop_index(batch_op.f('ix_quality_novelties_un_id'))
        batch_op.drop_index(batch_op.f('ix_quality_novelties_rule_type'))
        batch_op.drop_index(batch_op.f('ix_quality_novelties_package_id'))
        batch_op.drop_index(batch_op.f('ix_quality_novelties_element_type'))
        batch_op.drop_index(batch_op.f('ix_quality_novelties_element_guid'))

    op.drop_table('quality_novelties')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_sha256'))
        batch_op.drop_index(batch_op.f('ix_photos_package_id'))
        batch_op.drop_index(batch_op.f('ix_photos_element_guid'))

    op.drop_table('photos')
    with op.batch_alter_table('gis_staging_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gis_staging_elements_guid'))
        batch_op.drop_index(batch_op.f('ix_gis_staging_elements_batch_id'))

    op.drop_table('gis_staging_elements')
    with op.batch_alter_table('work_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_elements_work_id'))
        batch_op.drop_index(batch_op.f('ix_work_elements_element_guid'))

    op.drop_table('work_elements')
    with op.batch_alter_table('sync_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_packages_work_id'))
        batch_op.drop_index(batch_op.f('ix_sync_packages_un_id'))
        batch_op.drop_index(batch_op.f('ix_sync_packages_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_sync_packages_device_id'))

    op.drop_table('sync_packages')
    with op.batch_alter_table('remote_delete_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_delete_orders_work_id'))
        batch_op.drop_index(batch_op.f('ix_remote_delete_orders_un_id'))
        batch_op.drop_index(batch_op.f('ix_remote_delete_orders_status'))
        batch_op.drop_index(batch_op.f('ix_remote_delete_orders_device_id'))

    op.drop_table('remote_delete_orders')
    with op.batch_alter_table('gis_staging_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gis_staging_batches_work_id'))
        batch_op.drop_index(batch_op.f('ix_gis_staging_batches_un_code'))
        batch_op.drop_index(batch_op.f('ix_gis_staging_batches_status'))
        batch_op.drop_index(batch_op.f('ix_gis_staging_batches_queue_seq'))

    op.drop_table('gis_staging_batches')
    with op.batch_alter_table('field_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_changes_work_id'))
        batch_op.drop_index(batch_op.f('ix_field_changes_work_code'))
        batch_op.drop_index(batch_op.f('ix_field_changes_username'))
        batch_op.drop_index(batch_op.f('ix_field_changes_user_id'))
        batch_op.drop_index(batch_op.f('ix_field_changes_un_id'))
        batch_op.drop_index(batch_op.f('ix_field_changes_operation'))
        batch_op.drop_index(batch_op.f('ix_field_changes_element_guid'))

    op.drop_table('field_changes')
    with op.batch_alter_table('element_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_element_logs_element_id'))
        batch_op.drop_index(batch_op.f('ix_element_logs_element_guid'))

    op.drop_table('element_logs')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_work_type'))
        batch_op.drop_index(batch_op.f('ix_works_un_id'))
        batch_op.drop_index(batch_op.f('ix_works_status'))
        batch_op.drop_index(batch_op.f('ix_works_device_id'))
        batch_op.drop_index(batch_op.f('ix_works_code'))

    op.drop_table('works')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_revoked'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('quality_param_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_param_sets_version'))

    op.drop_table('quality_param_sets')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_un_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_uid'))
        batch_op.drop_index(batch_op.f('ix_devices_assigned_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_un_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_un_id'))

    op.drop_table('users')
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elements_un_id'))
        batch_op.drop_index(batch_op.f('ix_elements_parent_guid'))
        batch_op.drop_index(batch_op.f('ix_elements_guid'))
        batch_op.drop_index(batch_op.f('ix_elements_element_type'))

    op.drop_table('elements')
    with op.batch_alter_table('schema_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_definitions_version'))

    op.drop_table('schema_definitions')
    with op.batch_alter_table('business_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_units_code'))

    op.drop_table('business_units')
    # ### end Alembic commands ###
